### ISSUE TITLE
Stale details after VM restart

### ISSUE THREAD

**Issue by owenmather** [kevinkamps/Registrar#1] opened 2019-06-12 16:19 UTC
After a host restart registration to Consul has stale container details:

Attaching logs file: [registrar.log](https://github.com/kevinkamps/Registrar/files/3282225/registrar.log)

**Comment by kevinkamps** [comment] 2019-06-29 09:54
I'm working on this in branch [issues/1-stale-details-after-vm-restart/master](https://github.com/kevinkamps/Registrar/tree/issues/1-stale-details-after-vm-restart/master).

**Comment by kevinkamps** [comment] 2019-07-07 10:51
I wrote a fix that that tries to detect if the registrar is running in a container. If so that it would inspect the container at a fixed rate to see if something has changed. I tested this within my own VM to see if that would work and it did. But then i realised that it would actually restart the container on a vm reboot. That would mean that what code i wrote is not applicable and would not fix your issue. Because if the registrar fully restarts you should not have this issue. But with the current information i can not reproduce your issue. If you would be so kind to provide me with the following pieces of information:

- A inspect of the registrar container (`docker inspect <container_id>`) before restarting the vm
- A inspect of the registrar container (`docker inspect <container_id>`) after restarting the vm
- What OS is the VM running?

**Comment by kevinkamps** [comment] 2019-12-07 20:49
I talked with you about this offline and you could not reproduce your issue on your own environment so for now we decided to close this issue.

**Closed as completed by kevinkamps** 2019-12-07 20:49 UTC
